name: watheq_ecommerce
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  dartz: ^0.10.1
  dio: ^5.0.1
  bot_toast: ^4.0.3
  get_it: ^7.2.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.3
  url_launcher: 6.1.12
  shared_preferences: 2.2.0
  infinite_scroll_pagination: ^4.0.0 #TODO: if had enough time implement paginantion
  flutter_native_splash: 2.3.1
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  multi_select_flutter: ^4.1.3
  flutter_typeahead: ^4.8.0
  carousel_slider: ^4.2.1
  internet_connection_checker: ^1.0.0+1
  flutter_app_badger: ^1.5.0 # TODO: if you had enough time make also a badge on the app icon on the home screen with nom of notifications
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  firebase_remote_config: ^4.3.2
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/app_logo.png
  color: "#e1f5fe"
  color_dark: "#042a49"
  image_dark: assets/images/app_logo.png
  android_12:
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_logo.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/app_logo.png'
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - assets/translations/

  fonts:
    - family: BerkeleyStd
      fonts:
        - asset: assets/fonts/BerkeleyStd-Bold.otf
    - family: Sofia
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular-Az.otf
          weight: 400
        - asset: assets/fonts/Sofia-Pro-Medium-Az.otf
          weight: 500
        - asset: assets/fonts/Sofia-Pro-Bold-Az.otf
          weight: 700
    - family: Somar
      fonts:
        - asset: assets/fonts/Somar-Regular.ttf
          weight: 400
        - asset: assets/fonts/Somar-Medium.ttf
          weight: 500
        - asset: assets/fonts/Somar-Bold.ttf
          weight: 700